# Generated by Django 6.0.3 on 2026-03-17 14:02

import borrow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='returned',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('returned', 'Returned')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=borrow.models.default_due_date),
        ),
    ]
